### ISSUE TITLE
Use correct license

### ISSUE THREAD

**Issue by nonameolsson** [CongenialData/cdab-utils#13]
At the moment we use MIT as license. Make sure this is correct, otherwise change the license to the correct type.

**Comment by nonameolsson** [comment]
@thezic @djutemark vad tror ni om vilken typ av licens man ska använda? Jag har ingen erfarenhet av det. 

https://choosealicense.com

**Comment by thezic** [comment]
Tja, antingen MIT eller GPLv3. Jag tror nog det fungerar med MIT för komponentbilblioteket. Det betyder att alla får använda vår kod i komponentbiblioteket som de vill. Och det är väl inget i vårat bibliotek som är så unikt att det behöver skyddas väldigt, tänker jag mig.

Om vi vill "tvinga" de som använder vårat bilbiotek att bara använda det i projekt med öppen källkod får vi köra AGPL, GPLv3 eller något sådant.

Vad tycker ni?

**Comment by nonameolsson** [comment]
Bra motivering! Tycker MIT låter som en bra licens!

**Comment by djutemark** [comment]
Det står att det här projektet har licensen MIT, det går väl bra att stänga den här issuen? @nonameolsson

**Comment by nonameolsson** [comment]
@djutemark Yeah, you are right! We should use MIT. Found some more information about what is here https://choosealicense.com/licenses/mit/
