### ISSUE TITLE
Better development and contribution instructions

### ISSUE THREAD

**Issue by nonameolsson** [CongenialData/cdab-utils#14]
- [ ] Update the instructions in README.md
- [ ] Add CONTRIBUTIONS.md

**References**
https://gist.github.com/PurpleBooth/b24679402957c63ec426
https://medium.com/analytics-vidhya/getting-started-with-github-readme-md-bc348b943478
https://github.blog/2012-09-17-contributing-guidelines/

**Comment by gsonly** [comment]
I would like to help with this issue. How can I help?

**Comment by gsonly** [comment]
What update do I need to make for the instructions?

**Comment by nonameolsson** [comment]
> What update do I need to make for the instructions?

Thank you for helping out!

The file README.md contains som old instructions.

If you open package.json and play around with the different scripts, you will be able to figure out which ones should be used for developing.

You could add a section in the README with development instructions which should contain instructions on how to clone the repo, install dependencies and run the code locally. 

A part of how to link the local code, with npm link, to another project to try out the build would be also be great!
